export const categories = [
  "Housing",
  "Utility",
  "Loan Repayment",
  "Vehicle Repayment",
  "Vehicle Insurance",
  "Vehicle Maintenance",
  "Gas (Vehicle)",
  "Mobile",
  "Internet",
  "Property Tax",
  "Subscriptions",
  "Groceries",
  "Dine out",
  "Public Transportation",
  "Personal Care",
  "Entertainment",
  "Pet Food",
  "Investment",
];
